server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  client_max_body_size 2m;

  location /health {
    proxy_pass http://api:3001;
  }

  location /auth/ {
    proxy_pass http://api:3001;
  }

  location /me {
    proxy_pass http://api:3001;
  }

  location /games {
    proxy_pass http://api:3001;
  }

  location /matchmaking {
    proxy_pass http://api:3001;
  }

  location /ws {
    proxy_pass http://api:3001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_read_timeout 86400;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
